#!/bin/bash

KVM="/usr/bin/qemu"
META="-machine pc,accel=kvm -name WindowsXP -rtc base=localtime"
CPU="-cpu host -smp 2"
MEM="-m 1G"
DISK="-drive file=/data/winxp.qed,if=virtio,cache=none"
NET="-net user -net nic,model=virtio"
#VGA="-vga std"
AUDIO="-soundhw ac97"
POINTER="-usbdevice tablet"
#RDP="-net user,hostfwd=tcp::3389-:3389"

#modprobe kvm-intel
#pgrep qemu-kvm || ${KVM} ${META} ${CPU} ${MEM} ${DISK} ${NET} ${BALLON} ${VGA} ${AUDIO} ${POINTER} ${SPICE} ${RDP} ${VNC} -daemonize &
echo ${KVM} ${META} ${CPU} ${MEM} ${DISK} ${NET} ${BALLON} ${VGA} ${AUDIO} ${POINTER} ${SPICE} ${RDP} ${VNC} -daemonize &
#sudo ${KVM} ${META} ${CPU} ${MEM} ${HDA} ${USB} ${NET} -localtime #-usbdevice host:1483:c007

#exec spicec --host localhost --port 6789

