#!/bin/bash
[[ -f ./kernel/Makefile ]] && WORK=. || WORK=/usr/src/linux
pushd $WORK

echo "Making bzImage...."
export DISTCC_HOSTS='192.168.6.50,lzo'
make CC=distcc -j4 || exit

RELEASE=`<${WORK}/include/config/kernel.release`

mount /boot 2>&1 >/dev/null
echo "Installing kernel...."
echo -e "\t`cp -v arch/x86_64/boot/bzImage /boot/vmlinuz-${RELEASE}`"
echo -e "\t`cp -v .config /boot/config-${RELEASE}`"
echo -e "\t`cp -v .config /home/subi/repositories/conf/$(hostname)-config-${RELEASE}`"
echo -e "\t`cp -v System.map /boot/System.map-${RELEASE}`"

echo "Installing modules...."
make modules_install >/dev/null

echo "Update grub configuration...."
# work around for grub
pushd /dev
[[ -e root ]] || ln -s sda2 root
popd

if [[ -f /sbin/grub-mkconfig ]]; then
    read -r -d '' DEFAULT <<'EOF'
GRUB_DEFAULT="1"
GRUB_TIMEOUT="8"
GRUB_GFXMODE="1024x768"
GRUB_TERMINAL_OUTPUT="console"
LANG="zh_CN"

GRUB_DISTRIBUTOR="Exherbo"
GRUB_CMDLINE_LINUX="quiet resume=swap:/dev/sda3:0x74c000 printk.time=1"
GRUB_DISABLE_RECOVERY=true

GRUB_DISABLE_OS_PROBER=true
EOF
    eval ${DEFAULT} /sbin/grub-mkconfig -o /boot/grub/grub.cfg
else
    ${EDITOR} /boot/grub/grub.cfg
fi

umount /boot
