#!/bin/bash

# handler
INSTALLER=$([[ -d /efi ]] && echo systemd || manual)

# grub configurations
GRUB_CONFIG=/boot/grub/grub.cfg
BOOT_DEVICE="(hd0,gpt1)"
BOOT_DEVICE_UUID="1D89-D9BA"
LINUX_DEVICE="root=/dev/nvme0n1p2 ro rootflags=subvol=machines/exherbo"
KERNEL_OPTS=""

# common configurations
JOBS=$((`nproc` + 2))
RELEASE="unconfigured"

function build_kernel()
{
	echo "Making bzImage...."
	export PATH="/usr/libexec/distcc:${PATH}"
	export DISTCC_HOSTS='10.2.112.3,lzo'
	if make -j$JOBS; then
		RELEASE=`<${WORK}/include/config/kernel.release`
		return 0
	else
		return 1
	fi
}

function install_kernel()
{
	echo "Backing up kernel config..."
	echo -e "  `cp -v .config /data/base/system/conf/$(hostname)-config-${RELEASE}`"

	## /lib/modules
	echo "Installing modules...."
	eclectic alternatives update kmod-tools kmod # ensure kmod is selected since busybox breaks dracut
	make modules_install

	## /boot and /efi
	mount /boot
	case $INSTALLER in
		systemd)
			echo "Installing kernel (delegated to systemd)..."
			eclectic installkernel set systemd # ensure systemd provider of installkernel
			make install

			echo "Checking boot partition status..."
			mount /efi
			bootctl status
			umount /efi
			;;
		manual)
			echo "Installing kernel...."
			echo -e "\t`cp -v arch/x86_64/boot/bzImage /boot/exherbo/vmlinuz-${RELEASE}`"
			echo -e "\t`cp -v .config /boot/exherbo/config-${RELEASE}`"
			echo -e "\t`cp -v System.map /boot/exherbo/System.map-${RELEASE}`"

			echo "Installing Intel microcode..."
			echo -e "\t`cp -v /lib/firmware/microcode.cpio /boot/microcode.cpio`"

			echo "Generating and installing initramfs..."
			if which dracut 2>&1 >/dev/null; then
				dracut --xz --force /boot/exherbo/initramfs-${RELEASE}.img ${RELEASE}
			fi

			echo "Configuring grub..."
			if which grub-mkconfig 2>&1 >/dev/null; then
				do_my_grub_config > ${GRUB_CONFIG}	#do_grub_mkconfig
			else
				do_my_grub_config > ${GRUB_CONFIG}
				#    ${EDITOR} ${GRUB_CONFIG}
			fi
			;;
		*)
			;;
	esac
	umount /boot
}

function do_my_grub_config()
{
    cat <<'EOF'
if [ -s $prefix/grubenv ]; then
  load_env
fi

function load_video {
  if [ x$feature_all_video_module = xy ]; then
    insmod all_video
  else
    insmod efi_gop
    insmod efi_uga
    insmod ieee1275_fb
    insmod vbe
    insmod vga
    insmod video_bochs
    insmod video_cirrus
  fi
}

if loadfont unicode ; then
  set gfxmode=auto
  set gfxpayload=keep
  load_video
  insmod gfxterm
  set locale_dir=$prefix/locale
  set lang=zh_CN
  insmod gettext
fi
#terminal_output gfxterm
terminal_output console

set default=0
set timeout=8
set pager=1
EOF

#    generate_windows_entry
    generate_linux_entry
    generate_rescue_entry
}

function generate_windows_entry()
{
    cat <<EOF
menuentry 'Windows' {
        search --no-floppy --file --set=root /bootmgr
        chainloader +1
}
EOF
}

function generate_linux_entry()
{
	for kernel in `ls /boot/exherbo/vmlinuz* |sort -Vr`; do
		kernel=`basename ${kernel}`
		release=${kernel#vmlinuz-}
		cat <<EOF
menuentry 'Exherbo GNU/Linux, with Linux ${release}' --class exherbo --class gnu-linux --class gnu --class os {
  load_video
  insmod gzio
  insmod part_gpt
  insmod fat
  set root='${BOOT_DEVICE}'
  search --no-floppy --fs-uuid --set=root ${BOOT_DEVICE_UUID}
  echo   'Loading Linux ${release}...'
  linux  /exherbo/vmlinuz-${release} ${LINUX_DEVICE} ${KERNEL_OPTS}
  echo   'Loading initial ramdisk...'
  initrd /microcode.cpio /exherbo/initramfs-${release}.img
}
EOF
	done
}

function generate_rescue_entry()
{
	# [[ -d /boot/sysrcd ]] || return 0

	# https://www.system-rescue.org/manual/Installing_SystemRescue_on_the_disk/
	cat <<EOF
menuentry 'SystemRescue (loopback)' {
  iso_path='/sysresccd.iso'
  export iso_path
  search --set=root --file $iso_path
  # support booting recent GRUB versions on UEFI systems
  rmmod tpm
  loopback loop $iso_path
  set root=(loop)
  # the path below is on the SystemRescue ISO, not the hard drive
  configfile /boot/grub/loopback.cfg
}
menuentry 'Boot existing Linux System with SystemRescue Kernel (isoloop)' {
  load_video
  insmod gzio
  insmod part_gpt
  insmod fat
  search --no-floppy --fs-uuid --set=root ${BOOT_DEVICE_UUID}
  loopback loop /sysresccd.iso
  echo   'Loading kernel ...'
  linux  (loop)/sysresccd/boot/x86_64/vmlinuz img_label=boot img_loop=/sysresccd.iso archisobasedir=sysresccd findroot setkmap=dvorak
  echo   'Loading initramfs ...'
  initrd /microcode.cpio (loop)/sysresccd/boot/x86_64/sysresccd.img
}
EOF
}

[[ -f ./kernel/Makefile ]] && WORK=. || WORK=/usr/src/linux
pushd $WORK >/dev/null
build_kernel || exit 1
install_kernel || exit 1
popd  >/dev/null
